### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by giuseppeagostini-hotmart** [ahmadjoya/typescript-express-mongoose-starter#1]
Hi. I installed the project with the command: npx typescript-express-mongoose-starter <project-name>

When finishing and trying to run the project, I came across this error, and I am not able to solve it. There was no modification in the files, I just installed and tried to run.

Is there any step I must do to run the project?

```
yarn run v1.22.19
$ cross-env NODE_ENV=development nodemon
[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/* .env
[nodemon] watching extensions: js,ts,json
[nodemon] starting `ts-node -r tsconfig-paths/register --transpile-only src/server.ts`
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:115:11)
    at join (node:path:1172:7)
    at Object.<anonymous> (/Users/giuseppe.agostini/Documents/pessoal/tcc-connect-server/src/utils/logger.ts:8:28)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module.m._compile (/Users/giuseppe.agostini/Documents/pessoal/tcc-connect-server/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/giuseppe.agostini/Documents/pessoal/tcc-connect-server/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by andreidmour** [comment]
Same problem

**Comment by jkoutavas** [comment]
You need to add `LOG_DIR` to your .env file(s)

**Comment by ahmadjoya** [comment]
Hi. this is fixed in last update.

**Comment by ahmadjoya** [comment]
as this issue is resolved. I am closing it.
