### ISSUE TITLE
Request - Add Vercel Support

### ISSUE THREAD

**Issue by juliandurantini** [ahmadjoya/typescript-express-mongoose-starter#5]
Vercel is great for deploying Express apps like this. I am currently trying to deploy this to Vercel but running into issues. So far, I have in my vercel.json the below file contents, but I crash on deployment. I will continue debugging and report if I get it done, but no luck so far. 

vercel.json
{
  "version": 2,
  "builds": [
    {
      "src": "dist/server.js",
      "use": "@vercel/node",
      "config": {
        "includeFiles": [
          "dist/**"
        ]
      }
    }
  ],
  "routes": [
    {
      "src": "/(.*)",
      "dest": "dist/server.js",
      "methods": [
        "GET",
        "POST",
        "PUT",
        "DELETE",
        "PATCH",
        "OPTIONS"
      ],
      "headers": {
        "Access-Control-Allow-Credentials": "true",
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "GET,OPTIONS,PATCH,DELETE,POST,PUT",
        "Access-Control-Allow-Headers": "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version"
      }
    }
  ]
}

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at join (node:path:1171:7)
    at Object.<anonymous> (/var/task/dist/utils/logger.js:29:31)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at exports.c (/opt/node-bridge/chunk-DZ5MFMK4.js:1:1142)
    at /opt/node-bridge/bridge-server-CNJTFAIF.js:1:1443 {
  code: 'ERR_INVALID_ARG_TYPE'
}
INIT_REPORT Init Duration: 1521.69 ms	Phase: init	Status: error	Error Type: Runtime.ExitError
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at join (node:path:1171:7)
    at Object.<anonymous> (/var/task/dist/utils/logger.js:29:31)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at exports.c (/opt/node-bridge/chunk-DZ5MFMK4.js:1:1142)
    at /opt/node-bridge/bridge-server-CNJTFAIF.js:1:1443 {
  code: 'ERR_INVALID_ARG_TYPE'
}
INIT_REPORT Init Duration: 2368.55 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
Error: Runtime exited with error: exit status 1
Runtime.ExitError

**Comment by juliandurantini** [comment]
Update: I have gotten this working in Vercel after lots of trial and error. 

1. Add the following vercel.json file to the root directory: 
{
  "version": 2,
  "builds": [
    {
      "src": "dist/server.js",
      "use": "@vercel/node",
      "config": { "includeFiles": ["dist/**"] }
    }
  ],
  "routes": [
    {
      "src": "/(.*)",
      "dest": "dist/server.js",
      "methods": ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"],
      "headers": {
        "Access-Control-Allow-Credentials": "true",
        "Access-Control-Allow-Origin": "https://homegrown-front.vercel.app",
        "Access-Control-Allow-Methods": "GET,OPTIONS,PATCH,DELETE,POST,PUT",
        "Access-Control-Allow-Headers": "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version"
      }
    }
  ]
}

2. Add your environment variables in Vercel settings

3. Deploy! I can make a more detailed guide, if wanted!
